INSERT INTO node_tree (idNode, level, iLeft, iRight) VALUES (1, 2, 2, 3);
INSERT INTO node_tree (idNode, level, iLeft, iRight) VALUES (2, 2, 4, 5);
INSERT INTO node_tree (idNode, level, iLeft, iRight) VALUES (3, 2, 6, 7);
INSERT INTO node_tree (idNode, level, iLeft, iRight) VALUES (4, 2, 8, 9);
INSERT INTO node_tree (idNode, level, iLeft, iRight) VALUES (5, 1, 1, 24);
INSERT INTO node_tree (idNode, level, iLeft, iRight) VALUES (6, 2, 10, 11);
INSERT INTO node_tree (idNode, level, iLeft, iRight) VALUES (7, 2, 12, 19);
INSERT INTO node_tree (idNode, level, iLeft, iRight) VALUES (8, 3, 15, 16);
INSERT INTO node_tree (idNode, level, iLeft, iRight) VALUES (9, 3, 17, 18);
INSERT INTO node_tree (idNode, level, iLeft, iRight) VALUES (10, 2, 20, 21);
INSERT INTO node_tree (idNode, level, iLeft, iRight) VALUES (11, 3, 13, 14);
INSERT INTO node_tree (idNode, level, iLeft, iRight) VALUES (12, 2, 22, 23);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (1, 'english', 'Marketing', 1);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (2, 'italian', 'Marketing', 1);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (3, 'english', 'Helpdesk', 2);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (4, 'italian', 'Supporto tecnico', 2);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (5, 'english', 'Managers', 3);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (6, 'italian', 'Managers', 3);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (7, 'english', 'Customer Account', 4);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (8, 'italian', 'Assistenza Cliente', 4);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (9, 'english', 'Docebo', 5);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (10, 'italian', 'Docebo', 5);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (11, 'english', 'Accounting', 6);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (12, 'italian', 'Amministrazione', 6);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (13, 'english', 'Sales', 7);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (14, 'italian', 'Supporto Vendite', 7);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (15, 'english', 'Italy', 8);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (16, 'italian', 'Italia', 8);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (17, 'english', 'Europe', 9);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (18, 'italian', 'Europa', 9);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (19, 'english', 'Developers', 10);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (20, 'italian', 'Sviluppatori', 10);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (21, 'english', 'North America', 11);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (22, 'italian', 'Nord America', 11);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (23, 'english', 'Quality Assurance', 12);
INSERT INTO node_tree_names (id, language, nodeName, node_tree_idNode) VALUES (24, 'italian', 'Controllo Qualità', 12);