name: Release
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          git_committer_name: ${{ secrets.CI_GITHUB_USER }}
          git_committer_email: ${{ secrets.CI_GITHUB_EMAIL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # TODO: align develop
