name: Release
on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          root_options: "--config releaserc.toml"
          git_committer_name: ${{ secrets.CI_GITHUB_USER }}
          git_committer_email: ${{ secrets.CI_GITHUB_EMAIL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update develop
        run: |
          git checkout develop
          git rebase main
          git push
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
